Add config options to add and remove blocks as infusion stabilizers
rndmorris/Salis-Arcana pull request #46
Opened 2024-12-27 23:30 UTC by rndmorris

Resolves #41

2024-12-28 00:06 UTC, rndmorris commented
Please squash merge

2024-12-29 01:48 UTC, Midnight145 requested changes

2024-12-29 01:48 UTC, Midnight145 commented on src/main/java/dev/rndmorris/salisarcana/config/modules/BugfixesModule.java
> -            integerInfusionMatrixMath = new ToggleSetting(
This option should still exist on the off chance the other option is disabled, but only enabled if both itself is enabled and the new option is disabled

2024-12-29 01:48 UTC, Midnight145 commented on src/main/java/dev/rndmorris/salisarcana/config/settings/BlockItemListSetting.java
> +        if (entry.metadata > -1) {
should also probably check for 32767 (OreDictionary.WILDCARD_VALUE or whatever the constant is) here and tryAddItem

2024-12-29 01:48 UTC, Midnight145 commented on src/main/java/dev/rndmorris/salisarcana/config/settings/BlockItemListSetting.java
> +                    result.metadata = metadata;
might be worth just setting meta to 0 so you can get rid of some null checks elsewhere

2024-12-29 01:48 UTC, Midnight145 commented on src/main/java/dev/rndmorris/salisarcana/lib/InfusionMatrixLogic.java
> +        final var result = new MatrixSurroundingsResult();
Where's the definition for MatrixSurroundingResult? I'm on mobile so it's a pain for me to find anything.

2024-12-29 05:58 UTC, rndmorris commented on src/main/java/dev/rndmorris/salisarcana/config/modules/BugfixesModule.java
> -            integerInfusionMatrixMath = new ToggleSetting(
This isn't being removed, just internally renamed. It has the same key in the config file.

2024-12-29 06:07 UTC, rndmorris commented on src/main/java/dev/rndmorris/salisarcana/lib/InfusionMatrixLogic.java
> +        final var result = new MatrixSurroundingsResult();
It's further down in the same class. Its definition is
```java
public static class MatrixSurroundingsResult {

    public final ArrayList<ChunkCoordinates> pedestals = new ArrayList<>();
    public int symmetry = 0;
}
```

2024-12-29 06:07 UTC, rndmorris commented on src/main/java/dev/rndmorris/salisarcana/config/settings/BlockItemListSetting.java
> +                    result.metadata = metadata;
`result.metadata` is `int` with a default of `-1`, not `Integer`. The result of `IntegerHelper.tryParse(...)` is only null in the event of a failed parse. No further null checking required.

2024-12-29 06:07 UTC, rndmorris commented on src/main/java/dev/rndmorris/salisarcana/config/settings/BlockItemListSetting.java
> +        if (entry.metadata > -1) {
I'm not following what that would accomplish in this case. The lookup logic currently doesn't have any support for oredict stuff, but I could look into adding it.

2024-12-29 17:59 UTC, Midnight145 commented on src/main/java/dev/rndmorris/salisarcana/config/modules/BugfixesModule.java
> -            integerInfusionMatrixMath = new ToggleSetting(
I mean having a config option that's _just_ the integer math instead of the full rework, unless that's still there and i'm just not seeing it which is also possible

2024-12-29 18:00 UTC, Midnight145 commented on src/main/java/dev/rndmorris/salisarcana/config/settings/BlockItemListSetting.java
> +        if (entry.metadata > -1) {
The name is misleading, it's not actually oredictionary, it just allows for any metadata value and some people may use that assuming that leaving meta out defaults to 0, like with minetweaker scripts

2024-12-29 18:02 UTC, Midnight145 commented on src/main/java/dev/rndmorris/salisarcana/config/settings/BlockItemListSetting.java
> +                    result.metadata = metadata;
Oh true, not really sure how I missed that. I really shouldn't do code reviews while tired

2024-12-29 18:03 UTC, Midnight145 commented on src/main/java/dev/rndmorris/salisarcana/lib/InfusionMatrixLogic.java
> +        final var result = new MatrixSurroundingsResult();
Ahh, I see it now, didn't realize it was a nested class and missed it on my phone

2024-12-29 18:42 UTC, rndmorris commented on src/main/java/dev/rndmorris/salisarcana/config/settings/BlockItemListSetting.java
> +        if (entry.metadata > -1) {
Ahhh, okay. Yeah, I'll do that then.

2024-12-29 19:03 UTC, rndmorris commented on src/main/java/dev/rndmorris/salisarcana/config/modules/BugfixesModule.java
> -            integerInfusionMatrixMath = new ToggleSetting(
It's not. Having both the integer math and the full rework as options feels... I dunno, weird? Like, the integer math replaces just part of the method, but the rework replaces the whole thing *and* the rework

2024-12-29 19:07 UTC, Midnight145 commented on src/main/java/dev/rndmorris/salisarcana/config/modules/BugfixesModule.java
> -            integerInfusionMatrixMath = new ToggleSetting(
I think it's worth it because replacing the entire thing will kill any other modifications that any other mods do

2024-12-29 19:33 UTC, rndmorris commented on src/main/java/dev/rndmorris/salisarcana/config/modules/BugfixesModule.java
> -            integerInfusionMatrixMath = new ToggleSetting(
Do you think requiring the add/remove stabilizers feature to depend on the rework is reasonable? Because otherwise there really aren't any good injection points in the first half of the method to make that work

2024-12-29 20:17 UTC, Midnight145 commented on src/main/java/dev/rndmorris/salisarcana/config/modules/BugfixesModule.java
> -            integerInfusionMatrixMath = new ToggleSetting(
Oh yeah absolutely. I was thinking to have the integer math as it's own option that is disabled if the add/remove feature is enabled as that'll replace it

2024-12-30 21:36 UTC, rndmorris commented on src/main/java/dev/rndmorris/salisarcana/config/settings/BlockItemListSetting.java
> +        if (entry.metadata > -1) {
Done. It now defaults to 0 if metadata isn't specified or couldn't be parsed. As a shorthand, `*` will now be interpreted as the oredict wildcard value.

2024-12-30 21:37 UTC, rndmorris commented on src/main/java/dev/rndmorris/salisarcana/config/modules/BugfixesModule.java
> -            integerInfusionMatrixMath = new ToggleSetting(
Done. The rewrite is now tied into its own setting, and the integer math mixin has some logic on it to prevent it from loading alongside the rewrite mixin.

2024-12-30 23:53 UTC, Midnight145 approved these changes

2024-12-30 23:53 UTC, merged